stages:
  - build
  - deploy


build-staging:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind

  before_script:
    - docker login -u recru02 -p dE_wc1eopRsixMPnrumx registry.gitlab.com
    
  script:
    - docker build -f dockerfile.staging -t registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-staging .
    - docker push registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-staging

  only:
    - /^sprint-.*$/


build-master:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind

  before_script:
    - docker login -u recru02 -p dE_wc1eopRsixMPnrumx registry.gitlab.com
    
  script:
    - docker build -f dockerfile.production -t registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-production .
    - docker push registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-production

  only:
    - master


#section name
deploy-to-staging:
  stage: deploy
  image: ubuntu

  ## Terminal configurations for SSH
  before_script:
    ## Install ssh-agent if not already installed, it is required by Docker.
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'

    ## Run ssh-agent (inside the build environment)
    - eval $(ssh-agent -s)

    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

    ## Create the SSH directory and give it the right permissions
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    ## save ssh known_hosts (public key info) from the STAGING server
    - ssh-keyscan 52.250.22.66 >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

  script:
    - ssh admin-1@52.250.22.66 "sudo docker stop front-end"
    - ssh admin-1@52.250.22.66 "sudo docker rm front-end"
    - ssh admin-1@52.250.22.66 "sudo docker pull registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-staging:latest"
    - ssh admin-1@52.250.22.66 "sudo docker run --name front-end -it -d -p 3000:3000 registry.gitlab.com/sightly-engineering/content-intelligence/front-end/front-end-staging"

  only:
    - /^sprint-.*$/
