FROM node:12.13.1

ARG PORT=3000
ENV PORT=${PORT}

WORKDIR /app

COPY package.json /app

RUN npm install --force

COPY . /app

EXPOSE ${PORT}

HEALTHCHECK --interval=5s --timeout=2s --start-period=30s \
  CMD curl -I localhost:${PORT} || exit 1

CMD [ "npm", "run", "start-development" ]
