# File: googlecloudbuild-staging.yaml
steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-f', 'dockerfile.staging', '-t', 'gcr.io/$PROJECT_ID/front-end-staging', '.' ]
  # push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/front-end-staging']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'front-end-staging', '--image', 'gcr.io/$PROJECT_ID/front-end-staging', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']
