export const SET_ACCOUNTS = 'SET_ACCOUNTS'
export const SET_CURRENT_ACCOUNT_ID = 'SET_CURRENT_ACCOUNT_ID'
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'
export const SET_IS_SWITCHING_ACCOUNTS = 'SET_IS_SWITCHING_ACCOUNTS'
export const TREE_ACCOUNTS_CONVERT_DATA_SUCCESS =
	'TREE_ACCOUNTS_CONVERT_DATA_SUCCESS'
export const EDIT_ACCOUNT_ACCOUNT_USERS_LOADING =
	'EDIT_ACCOUNT_ACCOUNT_USERS_LOADING'
export const ACCOUNTS_SET_ACCOUNT_USERS = 'ACCOUNTS_SET_ACCOUNT_USERS'
export const SET_ACCOUNT_TYPES = 'SET_ACCOUNT_TYPES'
export const ACCOUNTS_UPDATE_ACCOUNT = 'ACCOUNTS_UPDATE_ACCOUNT'
export const ACCOUNTS_DELETE_ACCOUNT = 'ACCOUNTS_DELETE_ACCOUNT'
export const ACCOUNTS_CREATE_ACCOUNT = 'ACCOUNTS_CREATE_ACCOUNT'
export const SET_ACCOUNT_CREATED = 'SET_ACCOUNT_CREATED'

export const SET_ACCOUNT_SAVED = 'SET_ACCOUNT_SAVED'
export const SET_ACCOUNT_SAVING = 'SET_ACCOUNT_SAVING'
