export const BRAND_PROFILES_FETCH_DATA_SUCCESS =
	'BRAND_PROFILES_FETCH_DATA_SUCCESS'
export const REMOVE_BRAND_PROFILE = 'REMOVE_BRAND_PROFILE'
export const ADD_BRAND_PROFILE = 'ADD_BRAND_PROFILE'
export const BRAND_PROFILES_IS_LOADING = 'BRAND_PROFILES_IS_LOADING'
export const HAS_BRAND_PROFILES = 'HAS_BRAND_PROFILES'
export const SCENARIO_PROPERTIES_FETCH = 'SCENARIO_PROPERTIES_FETCH'
