export const ROLES_HAS_ERRORED = 'ROLES_HAS_ERRORED';
export const ROLES_PERMISSIONS_HAS_ERRORED = 'ROLES_PERMISSIONS_HAS_ERRORED';
export const ROLES_IS_LOADING = 'ROLES_IS_LOADING';
export const ROLES_PERMISSIONS_IS_LOADING = 'ROLES_PERMISSIONS_IS_LOADING';
export const ROLES_FETCH_DATA_SUCCESS = 'ROLES_FETCH_DATA_SUCCESS';
export const ROLES_PERMISSIONS_FETCH_DATA_SUCCESS = 'ROLES_PERMISSIONS_FETCH_DATA_SUCCESS';