export const USERS_HAS_ERRORED = 'USERS_HAS_ERRORED';
export const USERS_FETCH_DATA_SUCCESS = 'USERS_FETCH_DATA_SUCCESS';
export const DELETE_USER = 'DELETE_USER';
export const USER_DELETED = 'USER_DELETED';
export const USER_DELETED_ERROR = 'USER_DELETED_ERROR';
export const USERS_REMOVE_USER = 'USERS_REMOVE_USER';