export const SET_LISTS = 'SET_LISTS'
export const SET_LIST_ARCHIVED = 'SET_LIST_ARCHIVED'
export const SET_UPLOADED_LIST = 'SET_UPLOADED_LIST'
export const SET_IS_POSTING_LIST = 'SET_IS_POSTING_LIST'
export const SET_IS_POSTING_LIST_VERSION_ID = 'SET_IS_POSTING_LIST_VERSION_ID'
export const SET_POST_LIST_SUCCESS = 'SET_POST_LIST_SUCCESS'
export const SET_IS_FETCHING_LISTS = 'SET_IS_FETCHING_LISTS'
export const SET_FETCH_LISTS_SUCCESS = 'SET_FETCH_LISTS_SUCCESS'
export const SET_IS_DOWNLOADING_EXCEL = 'SET_IS_DOWNLOADING_EXCEL'
export const SET_IS_DOWNLOADING_EXCEL_VERSION_ID =
	'SET_IS_DOWNLOADING_EXCEL_VERSION_ID'

export const SET_LIST_VERSION_ACTIVE = 'SET_LIST_VERSION_ACTIVE'
export const SET_CREATED_LIST_VERSION = 'SET_CREATED_LIST_VERSION'
