export const CATEGORIES_FETCH_DATA_SUCCESS = 'CATEGORIES_FETCH_DATA_SUCCESS'
export const CHANNELS_FETCH_DATA_SUCCESS = 'CHANNELS_FETCH_DATA_SUCCESS'
export const VIDEOS_FETCH_DATA_SUCCESS = 'VIDEOS_FETCH_DATA_SUCCESS'