export const youtubeCategories = [
	{ categoryId: '32', categoryName: 'Action/Adventure' },
	{ categoryId: '31', categoryName: 'Anime/Animation' },
	{ categoryId: '2', categoryName: 'Autos & Vehicles' },
	{ categoryId: '33', categoryName: 'Classics' },
	{ categoryId: '34', categoryName: 'Comedy' },
	{ categoryId: '23', categoryName: 'Comedy' },
	{ categoryId: '35', categoryName: 'Documentary' },
	{ categoryId: '36', categoryName: 'Drama' },
	{ categoryId: '27', categoryName: 'Education' },
	{ categoryId: '24', categoryName: 'Entertainment' },
	{ categoryId: '37', categoryName: 'Family' },
	{ categoryId: '1', categoryName: 'Film & Animation' },
	{ categoryId: '38', categoryName: 'Foreign' },
	{ categoryId: '20', categoryName: 'Gaming' },
	{ categoryId: '39', categoryName: 'Horror' },
	{ categoryId: '26', categoryName: 'Howto & Style' },
	{ categoryId: '30', categoryName: 'Movies' },
	{ categoryId: '10', categoryName: 'Music' },
	{ categoryId: '25', categoryName: 'News & Politics' },
	{ categoryId: '29', categoryName: 'Nonprofits & Activism' },
	{ categoryId: '22', categoryName: 'People & Blogs' },
	{ categoryId: '15', categoryName: 'Pets & Animals' },
	{ categoryId: '40', categoryName: 'Sci-Fi/Fantasy' },
	{ categoryId: '28', categoryName: 'Science & Technology' },
	{ categoryId: '18', categoryName: 'Short Movies' },
	{ categoryId: '42', categoryName: 'Shorts' },
	{ categoryId: '43', categoryName: 'Shows' },
	{ categoryId: '17', categoryName: 'Sports' },
	{ categoryId: '41', categoryName: 'Thriller' },
	{ categoryId: '44', categoryName: 'Trailers' },
	{ categoryId: '19', categoryName: 'Travel & Events' },
	{ categoryId: '21', categoryName: 'Videoblogging' }
]

export const countries = [
	{ countryCode: 'AF', countryName: 'Afghanistan' },
	{ countryCode: 'AL', countryName: 'Albania' },
	{ countryCode: 'DZ', countryName: 'Algeria' },
	{ countryCode: 'AS', countryName: 'American Samoa' },
	{ countryCode: 'AD', countryName: 'Andorra' },
	{ countryCode: 'AO', countryName: 'Angola' },
	{ countryCode: 'AI', countryName: 'Anguilla' },
	{ countryCode: 'AQ', countryName: 'Antarctica' },
	{ countryCode: 'AG', countryName: 'Antigua and Barbuda' },
	{ countryCode: 'AR', countryName: 'Argentina' },
	{ countryCode: 'AM', countryName: 'Armenia' },
	{ countryCode: 'AW', countryName: 'Aruba' },
	{ countryCode: 'AU', countryName: 'Australia' },
	{ countryCode: 'AT', countryName: 'Austria' },
	{ countryCode: 'AZ', countryName: 'Azerbaijan' },
	{ countryCode: 'BS', countryName: 'Bahamas' },
	{ countryCode: 'BH', countryName: 'Bahrain' },
	{ countryCode: 'BD', countryName: 'Bangladesh' },
	{ countryCode: 'BB', countryName: 'Barbados' },
	{ countryCode: 'BY', countryName: 'Belarus' },
	{ countryCode: 'BE', countryName: 'Belgium' },
	{ countryCode: 'BZ', countryName: 'Belize' },
	{ countryCode: 'BJ', countryName: 'Benin' },
	{ countryCode: 'BM', countryName: 'Bermuda' },
	{ countryCode: 'BT', countryName: 'Bhutan' },
	{ countryCode: 'BO', countryName: 'Bolivia' },
	{ countryCode: 'BA', countryName: 'Bosnia and Herzegovina' },
	{ countryCode: 'BW', countryName: 'Botswana' },
	{ countryCode: 'BV', countryName: 'Bouvet Island' },
	{ countryCode: 'BR', countryName: 'Brazil' },
	{ countryCode: 'IO', countryName: 'British Indian Ocean Territory' },
	{ countryCode: 'VG', countryName: 'British Virgin Islands' },
	{ countryCode: 'BN', countryName: 'Brunei' },
	{ countryCode: 'BG', countryName: 'Bulgaria' },
	{ countryCode: 'BF', countryName: 'Burkina Faso' },
	{ countryCode: 'BI', countryName: 'Burundi' },
	{ countryCode: 'KH', countryName: 'Cambodia' },
	{ countryCode: 'CM', countryName: 'Cameroon' },
	{ countryCode: 'CA', countryName: 'Canada' },
	{ countryCode: 'CV', countryName: 'Cape Verde' },
	{ countryCode: 'KY', countryName: 'Cayman Islands' },
	{ countryCode: 'CF', countryName: 'Central African Republic' },
	{ countryCode: 'TD', countryName: 'Chad' },
	{ countryCode: 'CL', countryName: 'Chile' },
	{ countryCode: 'CN', countryName: 'China' },
	{ countryCode: 'CX', countryName: 'Christmas Island' },
	{ countryCode: 'CC', countryName: 'Cocos [Keeling] Islands' },
	{ countryCode: 'CO', countryName: 'Colombia' },
	{ countryCode: 'KM', countryName: 'Comoros' },
	{ countryCode: 'CD', countryName: 'Congo [DRC]' },
	{ countryCode: 'CG', countryName: 'Congo [Republic]' },
	{ countryCode: 'CK', countryName: 'Cook Islands' },
	{ countryCode: 'CR', countryName: 'Costa Rica' },
	{ countryCode: 'HR', countryName: 'Croatia' },
	{ countryCode: 'CU', countryName: 'Cuba' },
	{ countryCode: 'CY', countryName: 'Cyprus' },
	{ countryCode: 'CZ', countryName: 'Czech Republic' },
	{ countryCode: 'CI', countryName: "Côte d'Ivoire" },
	{ countryCode: 'DK', countryName: 'Denmark' },
	{ countryCode: 'DJ', countryName: 'Djibouti' },
	{ countryCode: 'DM', countryName: 'Dominica' },
	{ countryCode: 'DO', countryName: 'Dominican Republic' },
	{ countryCode: 'EC', countryName: 'Ecuador' },
	{ countryCode: 'EG', countryName: 'Egypt' },
	{ countryCode: 'SV', countryName: 'El Salvador' },
	{ countryCode: 'GQ', countryName: 'Equatorial Guinea' },
	{ countryCode: 'ER', countryName: 'Eritrea' },
	{ countryCode: 'EE', countryName: 'Estonia' },
	{ countryCode: 'ET', countryName: 'Ethiopia' },
	{ countryCode: 'FK', countryName: 'Falkland Islands [Islas Malvinas]' },
	{ countryCode: 'FO', countryName: 'Faroe Islands' },
	{ countryCode: 'FJ', countryName: 'Fiji' },
	{ countryCode: 'FI', countryName: 'Finland' },
	{ countryCode: 'FR', countryName: 'France' },
	{ countryCode: 'GF', countryName: 'French Guiana' },
	{ countryCode: 'PF', countryName: 'French Polynesia' },
	{ countryCode: 'TF', countryName: 'French Southern Territories' },
	{ countryCode: 'GA', countryName: 'Gabon' },
	{ countryCode: 'GM', countryName: 'Gambia' },
	{ countryCode: 'GZ', countryName: 'Gaza Strip' },
	{ countryCode: 'GE', countryName: 'Georgia' },
	{ countryCode: 'DE', countryName: 'Germany' },
	{ countryCode: 'GH', countryName: 'Ghana' },
	{ countryCode: 'GI', countryName: 'Gibraltar' },
	{ countryCode: 'GR', countryName: 'Greece' },
	{ countryCode: 'GL', countryName: 'Greenland' },
	{ countryCode: 'GD', countryName: 'Grenada' },
	{ countryCode: 'GP', countryName: 'Guadeloupe' },
	{ countryCode: 'GU', countryName: 'Guam' },
	{ countryCode: 'GT', countryName: 'Guatemala' },
	{ countryCode: 'GG', countryName: 'Guernsey' },
	{ countryCode: 'GN', countryName: 'Guinea' },
	{ countryCode: 'GW', countryName: 'Guinea-Bissau' },
	{ countryCode: 'GY', countryName: 'Guyana' },
	{ countryCode: 'HT', countryName: 'Haiti' },
	{ countryCode: 'HM', countryName: 'Heard Island and McDonald Islands' },
	{ countryCode: 'HN', countryName: 'Honduras' },
	{ countryCode: 'HK', countryName: 'Hong Kong' },
	{ countryCode: 'HU', countryName: 'Hungary' },
	{ countryCode: 'IS', countryName: 'Iceland' },
	{ countryCode: 'IN', countryName: 'India' },
	{ countryCode: 'ID', countryName: 'Indonesia' },
	{ countryCode: 'IR', countryName: 'Iran' },
	{ countryCode: 'IQ', countryName: 'Iraq' },
	{ countryCode: 'IE', countryName: 'Ireland' },
	{ countryCode: 'IM', countryName: 'Isle of Man' },
	{ countryCode: 'IL', countryName: 'Israel' },
	{ countryCode: 'IT', countryName: 'Italy' },
	{ countryCode: 'JM', countryName: 'Jamaica' },
	{ countryCode: 'JP', countryName: 'Japan' },
	{ countryCode: 'JE', countryName: 'Jersey' },
	{ countryCode: 'JO', countryName: 'Jordan' },
	{ countryCode: 'KZ', countryName: 'Kazakhstan' },
	{ countryCode: 'KE', countryName: 'Kenya' },
	{ countryCode: 'KI', countryName: 'Kiribati' },
	{ countryCode: 'XK', countryName: 'Kosovo' },
	{ countryCode: 'KW', countryName: 'Kuwait' },
	{ countryCode: 'KG', countryName: 'Kyrgyzstan' },
	{ countryCode: 'LA', countryName: 'Laos' },
	{ countryCode: 'LV', countryName: 'Latvia' },
	{ countryCode: 'LB', countryName: 'Lebanon' },
	{ countryCode: 'LS', countryName: 'Lesotho' },
	{ countryCode: 'LR', countryName: 'Liberia' },
	{ countryCode: 'LY', countryName: 'Libya' },
	{ countryCode: 'LI', countryName: 'Liechtenstein' },
	{ countryCode: 'LT', countryName: 'Lithuania' },
	{ countryCode: 'LU', countryName: 'Luxembourg' },
	{ countryCode: 'MO', countryName: 'Macau' },
	{ countryCode: 'MK', countryName: 'Macedonia [FYROM]' },
	{ countryCode: 'MG', countryName: 'Madagascar' },
	{ countryCode: 'MW', countryName: 'Malawi' },
	{ countryCode: 'MY', countryName: 'Malaysia' },
	{ countryCode: 'MV', countryName: 'Maldives' },
	{ countryCode: 'ML', countryName: 'Mali' },
	{ countryCode: 'MT', countryName: 'Malta' },
	{ countryCode: 'MH', countryName: 'Marshall Islands' },
	{ countryCode: 'MQ', countryName: 'Martinique' },
	{ countryCode: 'MR', countryName: 'Mauritania' },
	{ countryCode: 'MU', countryName: 'Mauritius' },
	{ countryCode: 'YT', countryName: 'Mayotte' },
	{ countryCode: 'MX', countryName: 'Mexico' },
	{ countryCode: 'FM', countryName: 'Micronesia' },
	{ countryCode: 'MD', countryName: 'Moldova' },
	{ countryCode: 'MC', countryName: 'Monaco' },
	{ countryCode: 'MN', countryName: 'Mongolia' },
	{ countryCode: 'ME', countryName: 'Montenegro' },
	{ countryCode: 'MS', countryName: 'Montserrat' },
	{ countryCode: 'MA', countryName: 'Morocco' },
	{ countryCode: 'MZ', countryName: 'Mozambique' },
	{ countryCode: 'MM', countryName: 'Myanmar [Burma]' },
	{ countryCode: 'NA', countryName: 'Namibia' },
	{ countryCode: 'NR', countryName: 'Nauru' },
	{ countryCode: 'NP', countryName: 'Nepal' },
	{ countryCode: 'NL', countryName: 'Netherlands' },
	{ countryCode: 'AN', countryName: 'Netherlands Antilles' },
	{ countryCode: 'NC', countryName: 'New Caledonia' },
	{ countryCode: 'NZ', countryName: 'New Zealand' },
	{ countryCode: 'NI', countryName: 'Nicaragua' },
	{ countryCode: 'NE', countryName: 'Niger' },
	{ countryCode: 'NG', countryName: 'Nigeria' },
	{ countryCode: 'NU', countryName: 'Niue' },
	{ countryCode: 'NF', countryName: 'Norfolk Island' },
	{ countryCode: 'KP', countryName: 'North Korea' },
	{ countryCode: 'MP', countryName: 'Northern Mariana Islands' },
	{ countryCode: 'NO', countryName: 'Norway' },
	{ countryCode: 'OM', countryName: 'Oman' },
	{ countryCode: 'PK', countryName: 'Pakistan' },
	{ countryCode: 'PW', countryName: 'Palau' },
	{ countryCode: 'PS', countryName: 'Palestinian Territories' },
	{ countryCode: 'PA', countryName: 'Panama' },
	{ countryCode: 'PG', countryName: 'Papua New Guinea' },
	{ countryCode: 'PY', countryName: 'Paraguay' },
	{ countryCode: 'PE', countryName: 'Peru' },
	{ countryCode: 'PH', countryName: 'Philippines' },
	{ countryCode: 'PN', countryName: 'Pitcairn Islands' },
	{ countryCode: 'PL', countryName: 'Poland' },
	{ countryCode: 'PT', countryName: 'Portugal' },
	{ countryCode: 'PR', countryName: 'Puerto Rico' },
	{ countryCode: 'QA', countryName: 'Qatar' },
	{ countryCode: 'RO', countryName: 'Romania' },
	{ countryCode: 'RU', countryName: 'Russia' },
	{ countryCode: 'RW', countryName: 'Rwanda' },
	{ countryCode: 'RE', countryName: 'Réunion' },
	{ countryCode: 'SH', countryName: 'Saint Helena' },
	{ countryCode: 'KN', countryName: 'Saint Kitts and Nevis' },
	{ countryCode: 'LC', countryName: 'Saint Lucia' },
	{ countryCode: 'PM', countryName: 'Saint Pierre and Miquelon' },
	{ countryCode: 'VC', countryName: 'Saint Vincent and the Grenadines' },
	{ countryCode: 'WS', countryName: 'Samoa' },
	{ countryCode: 'SM', countryName: 'San Marino' },
	{ countryCode: 'SA', countryName: 'Saudi Arabia' },
	{ countryCode: 'SN', countryName: 'Senegal' },
	{ countryCode: 'RS', countryName: 'Serbia' },
	{ countryCode: 'SC', countryName: 'Seychelles' },
	{ countryCode: 'SL', countryName: 'Sierra Leone' },
	{ countryCode: 'SG', countryName: 'Singapore' },
	{ countryCode: 'SK', countryName: 'Slovakia' },
	{ countryCode: 'SI', countryName: 'Slovenia' },
	{ countryCode: 'SB', countryName: 'Solomon Islands' },
	{ countryCode: 'SO', countryName: 'Somalia' },
	{ countryCode: 'ZA', countryName: 'South Africa' },
	{
		countryCode: 'GS',
		countryName: 'South Georgia and the South Sandwich Islands'
	},
	{ countryCode: 'KR', countryName: 'South Korea' },
	{ countryCode: 'ES', countryName: 'Spain' },
	{ countryCode: 'LK', countryName: 'Sri Lanka' },
	{ countryCode: 'SD', countryName: 'Sudan' },
	{ countryCode: 'SR', countryName: 'Suriname' },
	{ countryCode: 'SJ', countryName: 'Svalbard and Jan Mayen' },
	{ countryCode: 'SZ', countryName: 'Swaziland' },
	{ countryCode: 'SE', countryName: 'Sweden' },
	{ countryCode: 'CH', countryName: 'Switzerland' },
	{ countryCode: 'SY', countryName: 'Syria' },
	{ countryCode: 'ST', countryName: 'São Tomé and Príncipe' },
	{ countryCode: 'TW', countryName: 'Taiwan' },
	{ countryCode: 'TJ', countryName: 'Tajikistan' },
	{ countryCode: 'TZ', countryName: 'Tanzania' },
	{ countryCode: 'TH', countryName: 'Thailand' },
	{ countryCode: 'TL', countryName: 'Timor-Leste' },
	{ countryCode: 'TG', countryName: 'Togo' },
	{ countryCode: 'TK', countryName: 'Tokelau' },
	{ countryCode: 'TO', countryName: 'Tonga' },
	{ countryCode: 'TT', countryName: 'Trinidad and Tobago' },
	{ countryCode: 'TN', countryName: 'Tunisia' },
	{ countryCode: 'TR', countryName: 'Turkey' },
	{ countryCode: 'TM', countryName: 'Turkmenistan' },
	{ countryCode: 'TC', countryName: 'Turks and Caicos Islands' },
	{ countryCode: 'TV', countryName: 'Tuvalu' },
	{ countryCode: 'UM', countryName: 'U.S. Minor Outlying Islands' },
	{ countryCode: 'VI', countryName: 'U.S. Virgin Islands' },
	{ countryCode: 'UG', countryName: 'Uganda' },
	{ countryCode: 'UA', countryName: 'Ukraine' },
	{ countryCode: 'AE', countryName: 'United Arab Emirates' },
	{ countryCode: 'GB', countryName: 'United Kingdom' },
	{ countryCode: 'US', countryName: 'United States' },
	{ countryCode: 'UY', countryName: 'Uruguay' },
	{ countryCode: 'UZ', countryName: 'Uzbekistan' },
	{ countryCode: 'VU', countryName: 'Vanuatu' },
	{ countryCode: 'VA', countryName: 'Vatican City' },
	{ countryCode: 'VE', countryName: 'Venezuela' },
	{ countryCode: 'VN', countryName: 'Vietnam' },
	{ countryCode: 'WF', countryName: 'Wallis and Futuna' },
	{ countryCode: 'EH', countryName: 'Western Sahara' },
	{ countryCode: 'YE', countryName: 'Yemen' },
	{ countryCode: 'ZM', countryName: 'Zambia' },
	{ countryCode: 'ZW', countryName: 'Zimbabwe' }
]

export const languages = [
	{ languageCode: 'ab', languageName: 'Abkhazian' },
	{ languageCode: 'aa', languageName: 'Afar' },
	{ languageCode: 'af', languageName: 'Afrikaans' },
	{ languageCode: 'ak', languageName: 'Akan' },
	{ languageCode: 'sq', languageName: 'Albanian' },
	{ languageCode: 'am', languageName: 'Amharic' },
	{ languageCode: 'ar', languageName: 'Arabic' },
	{ languageCode: 'an', languageName: 'Aragonese' },
	{ languageCode: 'hy', languageName: 'Armenian' },
	{ languageCode: 'as', languageName: 'Assamese' },
	{ languageCode: 'av', languageName: 'Avaric' },
	{ languageCode: 'ae', languageName: 'Avestan' },
	{ languageCode: 'ay', languageName: 'Aymara' },
	{ languageCode: 'az', languageName: 'Azerbaijani' },
	{ languageCode: 'bm', languageName: 'Bambara' },
	{ languageCode: 'ba', languageName: 'Bashkir' },
	{ languageCode: 'eu', languageName: 'Basque' },
	{ languageCode: 'be', languageName: 'Belarusian' },
	{ languageCode: 'bn', languageName: 'Bengali' },
	{ languageCode: 'bh', languageName: 'Bihari languages' },
	{ languageCode: 'bi', languageName: 'Bislama' },
	{ languageCode: 'bs', languageName: 'Bosnian' },
	{ languageCode: 'br', languageName: 'Breton' },
	{ languageCode: 'bg', languageName: 'Bulgarian' },
	{ languageCode: 'my', languageName: 'Burmese' },
	{ languageCode: 'ca', languageName: 'Catalan' },
	{ languageCode: 'km', languageName: 'Central Khmer' },
	{ languageCode: 'ch', languageName: 'Chamorro' },
	{ languageCode: 'ce', languageName: 'Chechen' },
	{ languageCode: 'ny', languageName: 'Chichewa' },
	{ languageCode: 'zh', languageName: 'Chinese' },
	{ languageCode: 'cu', languageName: 'Church Slavic' },
	{ languageCode: 'cv', languageName: 'Chuvash' },
	{ languageCode: 'kw', languageName: 'Cornish' },
	{ languageCode: 'co', languageName: 'Corsican' },
	{ languageCode: 'cr', languageName: 'Cree' },
	{ languageCode: 'hr', languageName: 'Croatian' },
	{ languageCode: 'cs', languageName: 'Czech' },
	{ languageCode: 'da', languageName: 'Danish' },
	{ languageCode: 'dv', languageName: 'Divehi' },
	{ languageCode: 'nl', languageName: 'Dutch' },
	{ languageCode: 'dz', languageName: 'Dzongkha' },
	{ languageCode: 'en', languageName: 'English' },
	{ languageCode: 'eo', languageName: 'Esperanto' },
	{ languageCode: 'et', languageName: 'Estonian' },
	{ languageCode: 'ee', languageName: 'Ewe' },
	{ languageCode: 'fo', languageName: 'Faroese' },
	{ languageCode: 'fj', languageName: 'Fijian' },
	{ languageCode: 'fi', languageName: 'Finnish' },
	{ languageCode: 'fr', languageName: 'French' },
	{ languageCode: 'ff', languageName: 'Fulah' },
	{ languageCode: 'gd', languageName: 'Gaelic' },
	{ languageCode: 'gl', languageName: 'Galician' },
	{ languageCode: 'lg', languageName: 'Ganda' },
	{ languageCode: 'ka', languageName: 'Georgian' },
	{ languageCode: 'de', languageName: 'German' },
	{ languageCode: 'el', languageName: 'Greek' },
	{ languageCode: 'gn', languageName: 'Guarani' },
	{ languageCode: 'gu', languageName: 'Gujarati' },
	{ languageCode: 'ht', languageName: 'Haitian' },
	{ languageCode: 'ha', languageName: 'Hausa' },
	{ languageCode: 'he', languageName: 'Hebrew' },
	{ languageCode: 'hz', languageName: 'Herero' },
	{ languageCode: 'hi', languageName: 'Hindi' },
	{ languageCode: 'ho', languageName: 'Hiri Motu' },
	{ languageCode: 'hu', languageName: 'Hungarian' },
	{ languageCode: 'is', languageName: 'Icelandic' },
	{ languageCode: 'io', languageName: 'Ido' },
	{ languageCode: 'ig', languageName: 'Igbo' },
	{ languageCode: 'id', languageName: 'Indonesian' },
	{
		languageCode: 'ia',
		languageName: 'Interlingua (International Auxiliary Language Association)'
	},
	{ languageCode: 'ie', languageName: 'Interlingue' },
	{ languageCode: 'iu', languageName: 'Inuktitut' },
	{ languageCode: 'ik', languageName: 'Inupiaq' },
	{ languageCode: 'ga', languageName: 'Irish' },
	{ languageCode: 'it', languageName: 'Italian' },
	{ languageCode: 'ja', languageName: 'Japanese' },
	{ languageCode: 'jv', languageName: 'Javanese' },
	{ languageCode: 'kl', languageName: 'Kalaallisut' },
	{ languageCode: 'kn', languageName: 'Kannada' },
	{ languageCode: 'kr', languageName: 'Kanuri' },
	{ languageCode: 'ks', languageName: 'Kashmiri' },
	{ languageCode: 'kk', languageName: 'Kazakh' },
	{ languageCode: 'ki', languageName: 'Kikuyu' },
	{ languageCode: 'rw', languageName: 'Kinyarwanda' },
	{ languageCode: 'ky', languageName: 'Kirghiz' },
	{ languageCode: 'kv', languageName: 'Komi' },
	{ languageCode: 'kg', languageName: 'Kongo' },
	{ languageCode: 'ko', languageName: 'Korean' },
	{ languageCode: 'kj', languageName: 'Kuanyama' },
	{ languageCode: 'ku', languageName: 'Kurdish' },
	{ languageCode: 'lo', languageName: 'Lao' },
	{ languageCode: 'la', languageName: 'Latin' },
	{ languageCode: 'lv', languageName: 'Latvian' },
	{ languageCode: 'li', languageName: 'Limburgan' },
	{ languageCode: 'ln', languageName: 'Lingala' },
	{ languageCode: 'lt', languageName: 'Lithuanian' },
	{ languageCode: 'lu', languageName: 'Luba-Katanga' },
	{ languageCode: 'lb', languageName: 'Luxembourgish' },
	{ languageCode: 'mk', languageName: 'Macedonian' },
	{ languageCode: 'mg', languageName: 'Malagasy' },
	{ languageCode: 'ms', languageName: 'Malay' },
	{ languageCode: 'ml', languageName: 'Malayalam' },
	{ languageCode: 'mt', languageName: 'Maltese' },
	{ languageCode: 'gv', languageName: 'Manx' },
	{ languageCode: 'mi', languageName: 'Maori' },
	{ languageCode: 'mr', languageName: 'Marathi' },
	{ languageCode: 'mh', languageName: 'Marshallese' },
	{ languageCode: 'mn', languageName: 'Mongolian' },
	{ languageCode: 'na', languageName: 'Nauru' },
	{ languageCode: 'nv', languageName: 'Navajo' },
	{ languageCode: 'ng', languageName: 'Ndonga' },
	{ languageCode: 'ne', languageName: 'Nepali' },
	{ languageCode: 'nd', languageName: 'North Ndebele' },
	{ languageCode: 'se', languageName: 'Northern Sami' },
	{ languageCode: 'no', languageName: 'Norwegian' },
	{ languageCode: 'nb', languageName: 'Norwegian Bokmål' },
	{ languageCode: 'nn', languageName: 'Norwegian Nynorsk' },
	{ languageCode: 'oc', languageName: 'Occitan' },
	{ languageCode: 'oj', languageName: 'Ojibwa' },
	{ languageCode: 'or', languageName: 'Oriya' },
	{ languageCode: 'om', languageName: 'Oromo' },
	{ languageCode: 'os', languageName: 'Ossetian' },
	{ languageCode: 'pi', languageName: 'Pali' },
	{ languageCode: 'ps', languageName: 'Pashto' },
	{ languageCode: 'fa', languageName: 'Persian' },
	{ languageCode: 'pl', languageName: 'Polish' },
	{ languageCode: 'pt', languageName: 'Portuguese' },
	{ languageCode: 'pa', languageName: 'Punjabi' },
	{ languageCode: 'qu', languageName: 'Quechua' },
	{ languageCode: 'ro', languageName: 'Romanian' },
	{ languageCode: 'rm', languageName: 'Romansh' },
	{ languageCode: 'rn', languageName: 'Rundi' },
	{ languageCode: 'ru', languageName: 'Russian' },
	{ languageCode: 'sm', languageName: 'Samoan' },
	{ languageCode: 'sg', languageName: 'Sango' },
	{ languageCode: 'sa', languageName: 'Sanskrit' },
	{ languageCode: 'sc', languageName: 'Sardinian' },
	{ languageCode: 'sr', languageName: 'Serbian' },
	{ languageCode: 'sn', languageName: 'Shona' },
	{ languageCode: 'ii', languageName: 'Sichuan Yi' },
	{ languageCode: 'sd', languageName: 'Sindhi' },
	{ languageCode: 'si', languageName: 'Sinhala' },
	{ languageCode: 'sk', languageName: 'Slovak' },
	{ languageCode: 'sl', languageName: 'Slovenian' },
	{ languageCode: 'so', languageName: 'Somali' },
	{ languageCode: 'nr', languageName: 'South Ndebele' },
	{ languageCode: 'st', languageName: 'Southern Sotho' },
	{ languageCode: 'es', languageName: 'Spanish' },
	{ languageCode: 'su', languageName: 'Sundanese' },
	{ languageCode: 'sw', languageName: 'Swahili' },
	{ languageCode: 'ss', languageName: 'Swati' },
	{ languageCode: 'sv', languageName: 'Swedish' },
	{ languageCode: 'tl', languageName: 'Tagalog' },
	{ languageCode: 'ty', languageName: 'Tahitian' },
	{ languageCode: 'tg', languageName: 'Tajik' },
	{ languageCode: 'ta', languageName: 'Tamil' },
	{ languageCode: 'tt', languageName: 'Tatar' },
	{ languageCode: 'te', languageName: 'Telugu' },
	{ languageCode: 'th', languageName: 'Thai' },
	{ languageCode: 'bo', languageName: 'Tibetan' },
	{ languageCode: 'ti', languageName: 'Tigrinya' },
	{ languageCode: 'to', languageName: 'Tonga (Tonga Islands)' },
	{ languageCode: 'ts', languageName: 'Tsonga' },
	{ languageCode: 'tn', languageName: 'Tswana' },
	{ languageCode: 'tr', languageName: 'Turkish' },
	{ languageCode: 'tk', languageName: 'Turkmen' },
	{ languageCode: 'tw', languageName: 'Twi' },
	{ languageCode: 'ug', languageName: 'Uighur' },
	{ languageCode: 'uk', languageName: 'Ukrainian' },
	{ languageCode: 'ur', languageName: 'Urdu' },
	{ languageCode: 'uz', languageName: 'Uzbek' },
	{ languageCode: 've', languageName: 'Venda' },
	{ languageCode: 'vi', languageName: 'Vietnamese' },
	{ languageCode: 'vo', languageName: 'Volapük' },
	{ languageCode: 'wa', languageName: 'Walloon' },
	{ languageCode: 'cy', languageName: 'Welsh' },
	{ languageCode: 'fy', languageName: 'Western Frisian' },
	{ languageCode: 'wo', languageName: 'Wolof' },
	{ languageCode: 'xh', languageName: 'Xhosa' },
	{ languageCode: 'yi', languageName: 'Yiddish' },
	{ languageCode: 'yo', languageName: 'Yoruba' },
	{ languageCode: 'za', languageName: 'Zhuang' },
	{ languageCode: 'zu', languageName: 'Zulu' }
]
